### ISSUE TITLE
When a PersonaBar pane is opened, give focus to first focusable element inside it

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.AdminExperience#113]
## Description of problem
PR #110 adds keyboard navigation to the left hand menu portion of the PersonaBar. @valadas suggested when you open a Pane in the personabar (e.g. Site Settings), the first focusable item in that pane should receive focus. You could then pick up keyboard navigation from there.

It's not yet clear whether this could be done in one place, or if individual modules would need to implement it.

## Additional context
1. Open a pane in the PersonaBar (e.g. Site Settings)
2. First focuable element item in the pane is focussed (in Site Settings it would be the Site Title box)

## Affected version

All versions with PersonaBar.

## Affected browser
n/a

**Comment by OllyHodgson** [comment]
Adding the `autofocus` attribute to the first element would give it focus, but that would need to be implemented on a case by case basis. Not sure if there's a better way.

**Comment by bdukes** [comment]
My understanding is that `autofocus` only applies on the initial load of a page.  Elements dyanamically added to the page latest with `autofocus` wouldn't steal focus, AFAIK.  It seems like the routing piece in the Persona Bar framework would be able to introspect into the DOM of each panel as it loads them and focus on an element in the panel.

**Comment by OllyHodgson** [comment]
@bdukes Good point - so much of “old school” HTML stuff doesn’t apply for React apps!

**Comment by valadas** [comment]
Unless someone comes up with a better idea, we could on each module set the focus using javascript in the  componentDidMount() event. Does that make sense?

**Comment by valadas** [comment]
Oops, did not read you comment there @bdukes before my previous comment. The only thing is that each extension is different and the first component might not be focusable right? For instance the tabs are LI so they need a a tabindex to be focusable and they also have no active style so can't even see if it is focused or not, then I am not sure if enter would run the click action or what. And after the last element in the panel, pressing tab continues onto the elements of the actual page under the persona bar container. So yeah not sure what the correct solution is here.

**Comment by OllyHodgson** [comment]
@valadas I think we could use a fancy selector with `document.querySelector` to find the first focusable element, e.g. `input, textarea, select, a, button, [tabindex]`. Whether we’d need to put that into each module or in the routing piece we’ll have to find out!

The custom drop-down control used in the PB doesn’t seem to be focusable so that might need some work too.

**Comment by valadas** [comment]
I think many modules have tabs, if we modify that single component to be focus able then:
Create handlers for left and right arrows to switch tab. 
From there Pressing tab _should_ get us into the next form element. Which may be enough for most modules with a single change. For what's left (modules that have no tabs) then it could be a case by case issue...

The drop-down should also be another issue, I know the country drop-down does a strange thing, when using arrows it shows the ID instead of the country names. Not sure if all other drop-down do the same...

**Comment by OllyHodgson** [comment]
@valadas Maybe we add the 80px left margin on body as we know we're in edit mode? That way any loading delay won't mess with the rest of the site.

**Comment by valadas** [comment]
I had something nice with just css (I was just playing with this), but basically the persona bar would initially only show the Dnn logo and be semi-transparant until hovered. It would just partially cover 80x100 px on the top left corner where there is usually not much usable controls other than a logo that is usually larger than that.

When hovered it became opaque and grow down to show everything 100% opaque. That prevents the need for the 80px offset all together and was looking kinda nice. I did not submit that because it was hover only so not keyboard friendly. As soon as #110 is merged in, I will submit a pull request for that to get people opinion on it. Although it did not affect performance in any sort of way, it kinda felt faster since it was less visible and did not do any animation on page load. I call it performance by obfuscation :)

**Comment by valadas** [comment]
After digging a bit into similar stuff, moving focus programatically should be avoided where possible, opening the panel should not change focus but bring the panel as the next focusable elements in the sequence so that users can expand-collapse, then tab to the next ui item, basically the part that is wrong right now is that we rely on hover only in too many places. The items should be buttons or links (inherently focusable elements) and expanding a panel should be an action of cliking those. Then it adds the panel as the next html content and users can just tab into the next ui focusable element in order. I am closing this issue since there is already one open for this conversion of divs and spans into more semantic (and usable) elements that will also solve this.
