### ISSUE TITLE
Personabar lazy loading + caching

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.AdminExperience#14]
The method call 'gettable' (GET /API/personaBar/localization/gettable?culture=en-US HTTP/1.1) needs to be cached. Lazy loading would be even better. I personally use 'Strathweb.CacheOutput' and it works fine. So cache the web api methods with Strathweb.CacheOutput, e.g., [CacheOutput(ClientTimeSpan = 3600, ServerTimeSpan = 3600)].

Originally created by @kurtwilbies at https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/issues/192

**Comment by valadas** [comment]
In the spirit of cleaning up the backlog we are closing this issue due to the fact that it has been stale for quite some time. Also, we had some discussions and would like a solution that does not bring in extra external dependencies. On a related note, I have some ideas regarding localization that should improve this but it is a little bit on the backburner due to other more pressing issues.
