### ISSUE TITLE
Cannot edit price and billing frequency

### ISSUE THREAD

**Issue by ghost** [dnnsoftware/Dnn.AdminExperience#903]
In DNN 9.3.2 in edit roles fields like price and billing frequency cannot be edited anymore. This worked in 8.0.4. The Roles table is still intact.

**Comment by sleupold** [comment]
AFAIR, role billing had been deprecated in DNN 9.0

**Comment by ghost** [comment]
I still use that table and removing the ability to edit those fields cause problems.

**Comment by mitchelsellers** [comment]
Looking into the history on this a bit.  It appears there may have been an intention to remove this as part of 9.x.  However, the actual fields are not marked as Deprecated.

Overall, I believe that the backing functionality and usage of these fields is no longer necessary, the API's have not been updated to reflect it.  This is another one of those "confusing" things that weill need to be discussed.  I think also we should be flagging things as [Obsolete] if the decision is to remove it

**Comment by ghost** [comment]
To me, the functionality was missing because I am coming from 8.0.4. I will find another way of updating those fields if needed.

**Comment by valadas** [comment]
If my understanding is correct, all the backend still works (portals expire, etc.) but the UI was not migrated. 

So now we have to decide:
:A: We properly deprecate this now and remove it in 11
:B: We bring back a UI to manage it since it still works

Now, I have never used that feature, but for those who do, this would be a massive breaking change that may affect their business.

**Comment by valadas** [comment]
Since there was no reply, I gonna close this issue for cleanup reasons. If someone want's to bring that feature back, please open a new issue and indicated you are interested in contributing that.
